export interface TransactionInfo{
  id:number,
  primaryAccountNumber: string,
  processingCode: string,
  amountTransaction: bigint,
  localTransactionDateTime: Date,
  expirationDate: Date,
  pointOfServiceDataCode: string,
  cardSequenceNumber: string,
  functionCode: string,
  messageReasonCode: string,
  amountsOriginal: bigint,
  retrievalReferenceNumber: string,
  approvalCode: string,
  serviceCode: string,
  acceptorTerminalId: string,
  acceptorIdCode: string,
  acceptorNameLocation: string,
  currencyCodeTransaction: string,
  iccSystemRelatedData: string,
  transactionLifeCycleId: string,
  messageNumber: string,
  transactionDestinationInstitutionIdCode: string
}
